### ISSUE TITLE
Automate tests

### ISSUE THREAD

**Issue by Zelldon** [Zelldon/zdb#15]
With the new kotlin zdb we have integration tests with testcontainers, which I run locally.  It would be  a good next step if we automate them via github actions, like on each push or merge. 

Be aware that we might pull the docker image before running the tests, like we do in the c# client action https://github.com/camunda-community-hub/zeebe-client-csharp/blob/master/.github/workflows/aspnetcore.yml#L7

@korthout maybe something you want to start with

**Comment by korthout** [comment]
Sure! I'd be interested in this. I think I need a little tour of the new kotlin zdb first.

**Comment by Zelldon** [comment]
Done https://github.com/Zelldon/zdb/commit/c48f26a8b857ead35ead336bd47e117aca795d84
