### ISSUE TITLE
Support a filter for printed log records

### ISSUE THREAD

**Issue by korthout** [Zelldon/zdb#160]
When printing the log I can only print the entire log. This is problematic because sometimes I'm only interested in particular records.

Of course there are some workarounds:
- pipe into result `less` use its powerful search capabilities
- pipe into result `head` and `tail` to filter results

However, both solutions still suffer from:
- it's expensive and takes a long time
- an exception can occur because `zdb` is unable to print (e.g. unable to read) a particular record

I'd like to be able to indicate a `from` and `until` position as command options to control which records are printed.
I'd also like to be able to indicate a `number` of records as a command option to control how many records are printed.

**Comment by Zelldon** [comment]
Would you also be interested in value or record type filtering?

**Comment by korthout** [comment]
Yes, I guess there're many filters to consider. I'd appreciate any I could get my hands on 😆

**Comment by npepinpe** [comment]
What I would love is the conversation view like in Wireshark, i.e. being able to see only the records for a specific process instance, for example. That's a little tricky though, I'm sure :upside_down_face:

**Comment by Zelldon** [comment]
First filters added

 * https://github.com/Zelldon/zdb/pull/286
 * https://github.com/Zelldon/zdb/pull/285

Please create a separate FR if you need more :)
