### ISSUE TITLE
Do not deserialize records

### ISSUE THREAD

**Issue by Zelldon** [Zelldon/zdb#171]
> Really great Idea because I realized we don't even need to use the event registry! Since it is msgpack we can directly convert it to json ! Thanks @korthout I will change it when I have time
> 
> Example: `MsgPackConverter.convertToJson(UnsafeBuffer(loggedEvent.valueBuffer, loggedEvent.valueOffset, loggedEvent.valueLength))`

_Originally posted by @Zelldon in https://github.com/Zelldon/zdb/pull/169#discussion_r937408309_

**Comment by Zelldon** [comment]
Fixed by #311

**Comment by korthout** [comment]
Late reply, but better late than never. Thanks @Zelldon ❤️ Awesome improvements!
