### ISSUE TITLE
zdb status variables output should show units for values

### ISSUE THREAD

**Issue by korthout** [Zelldon/zdb#3]
`zdb status` shows min size, max size and avg size but does not display a unit for these values. I assume it is bytes, but it's unclear. Please add units to these values.

Example:
```
Variables: 2769
	min size: 1 B
	max size: 4.7 KB
	avg size: 46.16793 B
```

**Comment by Zelldon** [comment]
It is always in bytes. Since the output is now json this is not easy to implement. We could rename the properties to have the unit in it.
