### ISSUE TITLE
Best-effort decoding of keys in all column families

### ISSUE THREAD

**Issue by oleschoenburg** [Zelldon/zdb#369]
Extending https://github.com/Zelldon/zdb/commit/27636a18089afad79d6baad1f44893ff41f73abc, it would be nice if zdb would provide a number of default decoders for all column families.

Since key format may change from time to time, and decoding may be expensive, we should offer an opt-out to display the hex value instead.

Additionally, we could allow arbitrary decoding, for example by providing the key structure via a CLI parameter. Something like `zbd list -cf MESSAGE_SUBSCRIPTION_BY_NAME_AND_CORRELATION_KEY -kf ssl` where -kf stands for key-format and `ssl` specifies that keys are in the format `DbString + DbString + DbLong`.

**Comment by oleschoenburg** [comment]
Reopened so that we have an issue for adding the decoders for **all** column families.

**Comment by Zelldon** [comment]
Could also use https://github.com/Zelldon/zdb/issues/354 🤷🏼
