### ISSUE TITLE
Fix zdb for zeebe 1.x versions

### ISSUE THREAD

**Issue by korthout** [Zelldon/zdb#9]
There were some breaking changes between 0.26 and the upcoming 1.0.0. zdb should be able to work with 1.0.0

**Comment by Zelldon** [comment]
I started to rewrote zdb in kotlin. It doesn't support the same features as the old one, but it is a good start. I was able to write integration tests with testcontainers. I created follow up issues to align with the old zdb version (in terms of features)


 * https://github.com/Zelldon/zdb/issues/14
 * https://github.com/Zelldon/zdb/issues/12
 * https://github.com/Zelldon/zdb/issues/13
 * https://github.com/Zelldon/zdb/issues/11

**Comment by Zelldon** [comment]
done
